name: car_rent
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Localization (الصحيح فقط)
  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  line_icons: ^2.0.2
  get_it: ^8.2.0
  google_fonts: ^6.2.0
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.2
  shared_preferences: ^2.5.3
  syncfusion_flutter_datepicker: ^31.1.19
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  material_symbols_icons: ^4.2874.0
  google_nav_bar: ^5.0.7
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  meta: ^1.16.0
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^5.1.1
  go_router: ^17.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0        # <-- تم نقله هنا
  mocktail: ^1.0.0          # For creating mocks in tests
  build_runner: ^2.4.13
  hive_generator: ^2.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true # <<<<<< ضروري للـ l10n

  assets:
    - lib/assets/images/

gen-l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
